name: publish

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: bkuhl/php
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: 'refs/tags/v1.0.4'
          version_extractor_regex: '\/v(.*)$'
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
#          push: true
          tags: $REGISTRY:latest,$REGISTRY:${{ steps.semver_parser.outputs.major }},$REGISTRY:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }},$REGISTRY:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}